### ISSUE TITLE
Feature Request: Take input as command line parameters

### ISSUE THREAD

**Issue by sadn1ck** [soham0-0/Morse-Code-Decoder#1]
argc, argv etc, so

```bash
$ morsedecode ...-..-...--
idk what the output should be so
```

also add release binaries to releases tab

**Comment by soham0-0** [comment]
Thank You for the suggestions. I have made the changes.

![59349318](https://user-images.githubusercontent.com/62219251/94472682-b8d5ec80-01e8-11eb-83ef-0cc4876b7f23.jpg)
