### ISSUE TITLE
Add help section

### ISSUE THREAD

**Issue by soham0-0** [soham0-0/Morse-Code-Decoder#3]
for example, for git it looks like follows: 

![asaddc](https://user-images.githubusercontent.com/62219251/94857180-ba085300-044e-11eb-9912-4941afb900c7.JPG)

**Comment by sgavil** [comment]
Hello, what is this issue about? Can you explain it more?

**Comment by soham0-0** [comment]
### Ok. So what i am saying is something like this :

![asaddc](https://user-images.githubusercontent.com/62219251/94857121-a0670b80-044e-11eb-892c-edb6ade6c056.JPG)
